import { EmbedBuilder, SlashCommandBuilder } from "discord.js";
import Replicate from "replicate";
import configJSON from "../../../config.json" assert { type: 'json' };
import { setTimeout } from "node:timers/promises";
import prompts from "prompts";

const replicate = new Replicate({
    auth: configJSON.replicateKey
});

export const data = new SlashCommandBuilder()
    .setName('gen-image')
    .setDescription('Replies with Pong!')
    .addStringOption(option => 
    option
        .setName('prompt')
        .setDescription('Describe the image you want to generate!')
        .setRequired(true)
    );
export async function execute(interaction, client) {

    await interaction.deferReply();

    const imgPrompt = interaction.options.getString('prompt')

    const output = await replicate.run(
        "stability-ai/sdxl:39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b",
        {
          input: {
            width: 768,
            height: 768,
            prompt: imgPrompt,
          }
        }
      );

    const linkOutput = output[0];

    const outputEmbed = new EmbedBuilder()
    .setAuthor({ name: interaction.user.username, iconURL: interaction.user.displayAvatarURL() })
    .setDescription(interaction.options.getString('prompt'))
    .setImage(`${linkOutput}`)
    .setFooter({ iconURL: client.user.displayAvatarURL(), text: "Generated by ReplicateAPI"  })

    await interaction.editReply({ embeds: [outputEmbed] });
}